### ISSUE TITLE
Поправить запись на урок с часовыми поясами

### ISSUE THREAD

**Issue by kamenskiyyyy** [School-Just-Study/crm-and-site-just-study#506]

**Comment by geocheck123** [comment]
починить систему записи на занятия (избавиться от бага с расписанием, возможность админу легко вручную записывать ученика по постоянному повторяющемуся расписанию, чтобы всегда корректно работал перенос/отмена занятий, сделать удобную работу с часовыми поясами, чтобы корректно работало)

**Comment by kamenskiyyyy** [comment]
eachMinuteOfInterval step = 30

**Comment by kamenskiyyyy** [comment]
Необходимо перенести логику генерации свободных слотов с фронта на бек для безопасности 

<!-- Uploading "image.png"... —>
